name: CI

on:
  push:
    branches: [ main, engage/feature ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (needed for Firestore emulator)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install functions deps
        working-directory: ./functions
        run: npm install --no-audit --no-fund

      - name: Install firebase-tools
        run: npm install -g firebase-tools@11

      - name: Start Firestore emulator
        run: |
          firebase emulators:start --only firestore --project demo --host 127.0.0.1 --port 8080 &
          npx wait-on tcp:127.0.0.1:8080
        env:
          FIREBASE_PROJECT: demo

      - name: Run tests
        working-directory: ./functions
        env:
          FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080
        run: npm test
